<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <style>
        body{
            text-align: center;
        }
        h1{
            margin: 20px auto;
        }
    </style>
</head>
<body>
    <h1>ABOUT</h1>
    <p>My Name : <?= $name; ?></p>
    <p>Umur : <?= $usia; ?></p>
</body>
</html>