<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
</head>
<body>
    <form action="/form-process" method="post">
        <label for="uname">Username</label>
        <input type="text" name="uname" id="uname">
        <label for="posisi">Posisi</label>
        <input type="text" name="posisi" id="posisi">
        <!-- <input type="file" name="file" id="file"> -->
        <button>Kirim</button>
    </form>
</body>
</html>