<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            /* h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            } */
        </style>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </head>
    <!-- <script type="text/javascript">
    $(window).on('load', function() {
        $('#contoh').modal('show');
    });
</script> -->
    <body class="text-center">
        <h1 class="display-1">Slim</h1>
        <div>a microframework for PHP</div>

        <?php 
        // session_start();
        if (isset($_SESSION['name'])) : ?>
            <h2>Hello <?= htmlspecialchars($_SESSION['name']); ?>!</h2>
        <?php else: ?>
            <!-- <script>
               alert('kamu belum login')
               windows.location.href='/login' 
            </script> -->
            <!-- <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p> -->
        <?php endif; ?>
        <a href="/logout-process">Logout</a>
        <h1 class="display-2">Data Customer</h1>
        <?php
            if(isset($spesific)){
                ?> 
                    <div class="container d-flex justify-content-center">
                        <div class="card">
                            <div class="card-header">
                                <h1 class="display-3">Deskripsi Data</h1>
                                <a href="/<?= $id; ?>/update" class="btn btn-warning">Update Data</a>
                            </div>
                            <?php
                                $s = 0;
                                foreach($search as $sc){
                                    foreach($column as $cl){
                                    ?>
                                    <div class="card-body row">
                                        <div class="col-6">
                                            <p class="lead fw-bold"><?= $cl['COLUMN_NAME'] ?> </p>
                                        </div>
                                        <div class="col-1">
                                            <p class="lead">: </p>
                                        </div>
                                        <div class="col-5">
                                            <p class="lead"><?= $sc[$cl['COLUMN_NAME']] ?></p>
                                        </div>
                                    </div>
                                    <?php
                                    $s++;
                                    }
                                }
                            ?>
                        </div>
                    </div>
                <?php
            }
        ?>
        <?php
            if(isset($update)){
                ?> 
                    <div class="container d-flex justify-content-center">
                        <div class="card">
                            <form action="/update" method="post">
                                
                                <div class="card-header">
                                    <h3 class="display-5">Update Data</h3>
                                </div>
                                <?php
                                    $s = 0;
                                    foreach($search as $sc){
                                        foreach($column as $cl){
                                        ?>
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-6">
                                                    <p class="lead fw-bold"><?= $cl['COLUMN_NAME'] ?> </p>
                                                </div>
                                                <div class="col-1">
                                                    <p class="lead">: </p>
                                                </div>
                                                <div class="col-5">
                                                    <!-- <p class="lead"><?= $sc[$cl['COLUMN_NAME']] ?></p> -->
                                                    <input type="text" class="form-control" name="<?= $cl['COLUMN_NAME'] ?>" value="<?= $sc[$cl['COLUMN_NAME']] ?>">
                                                </div>
                                            </div>
                                        </div>

                                        <?php
                                        $s++;
                                        }
                                    }
                                ?>
                                
                                <input type="submit" value="update" class="btn btn-primary">
                                <!-- <input type="reset" value="Reset"> -->
                                <a href="/" class="btn btn-danger">Close</a>
                            </form>
                        </div>
                    </div>
                <?php
            }
        ?>
        <?php
            if(isset($insert)){
                ?> 
                    <div class="container d-flex justify-content-center">
                        <div class="card">
                            <form action="/insert" method="post">
                                
                                <div class="card-header">
                                    <h3 class="display-5">Insert Data</h3>
                                </div>
                                <?php
                                    $s = 0;
                                        foreach($column as $cl){
                                            if($cl['COLUMN_NAME'] == "CUST_CODE") continue;
                                        ?>
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-6">
                                                    <p class="lead fw-bold"><?= $cl['COLUMN_NAME'] ?> </p>
                                                </div>
                                                <div class="col-1">
                                                    <p class="lead">: </p>
                                                </div>
                                                <div class="col-5">
                                                    <!-- <p class="lead"><?= $sc[$cl['COLUMN_NAME']] ?></p> -->
                                                    <input type="text" class="form-control" name="<?= $cl['COLUMN_NAME'] ?>">
                                                </div>
                                            </div>
                                        </div>

                                        <?php
                                        $s++;
                                        }
                                    
                                ?>
                                
                                <input type="submit" value="insert" class="btn btn-primary">
                                <!-- <input type="reset" value="Reset"> -->
                                <a href="/" class="btn btn-danger">Close</a>
                            </form>
                        </div>
                    </div>
                <?php
            }
        ?>
        <a href="/insert" class="btn btn-primary">Insert New Data</a>
        <form action="" method="post">
            <table class="table">
                <thead>
                <th scope="col">#</th>
                <th scope="col">Nama</th>
                </thead>
                <tbody>
                <?php
                    // $data = $container->db->query($conn,'SELECT CUST_CODE id, CUST_NAME nama FROM customer');
                    $i = 1;
                    foreach($data as $res){
                        ?>
                        <tr>
                            <td scope="row"><a  href="/<?= $res['CUST_CODE']; ?>/select"><?= $res['CUST_CODE'];?></a></td>
                            <!-- <td><a href="/<?= $res['CUST_CODE']; ?>"><?= $res['CUST_NAME']; ?></a></td> -->
                            <td><a href="/<?= $res['CUST_CODE']; ?>/select" ><?= $res['CUST_NAME']; ?></a></td>
                            <td><a href="/<?= $res['CUST_CODE']; ?>/delete" >Delete data</a></td>
                        </tr>
                        <?php
                        $i++;
                    }
                ?>
                </tbody>
            </table> 
            
        </form>   
        <?php
            if(isset($modal)){
                require('modal.phtml');
            }
        ?> 
    </body>
</html>
